name: Build

on:
  push:
    branches: [ master, dev ]
    # 仅在相关文件变更时触发，减少不必要的构建
    paths:
      - '**.js'
      - '**.ts'
      - '**.json'
      - 'yarn.lock'
      - '.github/workflows/build.yml'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read  # 最小权限原则

    strategy:
      matrix:
        node-version: [20.x]
        # 可添加更多Node版本测试，如 [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4  # 升级到最新稳定版
        with:
          fetch-depth: 1  # 仅拉取最新提交，加快速度

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4  # 升级到最新版
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'  # 自动缓存yarn依赖，加速安装

      - name: Get dependencies
        run: yarn install --frozen-lockfile  # 锁定依赖版本，确保一致性
        env:
          # 可选：设置npm registry加速依赖下载
          npm_config_registry: https://registry.npm.taobao.org

      - name: Lint (可选)
        run: yarn lint  # 若项目有lint脚本，可添加代码检查步骤

      - name: Build
        run: yarn build
        env:
          # 可添加构建所需的环境变量
          NODE_ENV: production

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.node-version }}  # 包含Node版本，便于多版本测试
          path: dist/
          retention-days: 7  #  artifacts保留7天，节省存储空间
          if-no-files-found: error  # 若dist目录为空则报错